### ISSUE TITLE
Where does the import_config_${KTO} comes from?

### ISSUE THREAD

**Issue by mrwsl** [devfaz/firefly-iii-dkb#4]
Thank you for this repository—it is precisely what I needed. As the title says, I wonder where the import config comes from.

**Comment by mrwsl** [comment]
Never mind - you get the JSON from manually importing the CSV once.

**Comment by mrwsl** [comment]
One question remains, though: How do you map the `ultimatedebtor` in your import?

**Comment by devfaz** [comment]
@herrwusel 
```
ultimateDebtor == Opposing Account (name)
```

**Comment by Brandt1930** [comment]
> Never mind - you get the JSON from manually importing the CSV once.

Hi @mrwsl  what do you mean by importing the CSV manually?

**Comment by mrwsl** [comment]
Iirc I had to manually go through the assigning process and was able to get the JSON in the end.
